name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean createInstaller
      - name: Prepare artifact archival
        run: mkdir staging && cp build/distributions/*-install.exe staging
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
